name: Cypress CI
# Controls when the workflow will run
on: 
  push:
    branches:
      - main
  # Triggers the workflow on push or pull request events but only for the main branch
 jobs:
  cypress-run:
    runs-on:  ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Cypress run
          # You may pin to the exact commit or the version.
          # uses: cypress-io/github-action@30008f1458a5a2c97054bfe118fe33d75976c482
        uses: cypress-io/github-action@v4.2.0
          with:
            build: npm run build
            start: npm start
